# Reproducibility Configuration
seeds:
  global_seed: 42
  numpy_seed: 42
  torch_seed: 42
  cuda_seed: 42

# Model Configuration
model:
  name: "resnet50"
  pretrained: true
  num_classes: 4  # glioma, meningioma, notumor, pituitary

# Data Configuration
data:
  dataset_name: "brainmri_4c"
  image_size: [224, 224]
  batch_size: 32
  num_workers: 4
  classes: ["glioma", "meningioma", "notumor", "pituitary"]
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

# Training Configuration
training:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 1e-4
  scheduler: "cosine"
  early_stopping_patience: 10

# Augmentation Configuration
augmentation:
  horizontal_flip: 0.5
  vertical_flip: 0.2
  rotation_limit: 15
  brightness_contrast: 0.2
  gaussian_noise: 0.1

# Paths Configuration
paths:
  data_dir: "data/"
  dataset_dir: "data/brainmri_4c/"
  train_dir: "data/brainmri_4c/training/"
  test_dir: "data/brainmri_4c/testing/"
  raw_data_dir: "data/raw/"
  processed_data_dir: "data/processed/"
  models_dir: "experiments/models/"
  logs_dir: "experiments/logs/"
  figures_dir: "figs/"
  checkpoints_dir: "experiments/checkpoints/"

# Hardware Configuration
hardware:
  device: "auto"  # auto, cpu, cuda
  mixed_precision: true
  deterministic: true

# Logging Configuration
logging:
  level: "INFO"
  log_every_n_steps: 10
  save_model_every_n_epochs: 5

# Experiment Configuration
experiment:
  name: "brainmri_4c_baseline"
  tags: ["baseline", "medical_imaging", "brain_mri", "tumor_classification"]
  notes: "Brain MRI 4-class tumor classification: glioma, meningioma, notumor, pituitary"
